image: docker:latest

services:
  - docker:dind

stages:
  - "Minimize"

docker-slim:
  stage: "Minimize"
  script:
    - apk add -U zip curl 
    - curl -L -o /tmp/dist_linux.tar.gz https://github.com/docker-slim/docker-slim/releases/download/1.23/dist_linux.tar.gz && tar xvzf /tmp/dist_linux.tar.gz -C /usr/local/bin --strip-components 1
    - docker-slim version
    # - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    # - docker pull ubuntu:14.04
