image: docker:latest

services:
  - docker:dind

stages:
  - "Minimize"

build:
  stage: "Minimize"
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build --compress --squash -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  
docker-slim:
  stage: "Minimize"
  script:
    - apk add -U zip curl 
    - curl -L -o /tmp/dist_linux.tar.gz https://github.com/docker-slim/docker-slim/releases/download/1.23/dist_linux.tar.gz && tar xvzf /tmp/dist_linux.tar.gz -C /usr/local/bin --strip-components 1
    - ls -lh /usr/local/bin/docker-slim-sensor
    - chmod +x /usr/local/bin/docker-slim-sensor
    - docker pull ubuntu:14.04
    - docker-slim build --tag "$CI_REGISTRY_IMAGE" ubuntu:14.04 
