image: docker:latest

services:
  - docker:dind

stages:
  - "Minimize"

docker-slim:
  stage: "Minimize"
  script:
    - apk add -U zip curl 
    - curl -L -o /tmp/tflint.zip https://github.com/wata727/tflint/releases/download/v0.7.2/tflint_linux_amd64.zip && unzip /tmp/tflint.zip -d /usr/local/bin
    # - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    # - docker pull ubuntu:14.04
